language: python
python:
  - "2.7"
# command to run tests
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install coverage
script:
  - nosetests --with-coverage --cover-package=app
  
after_success:  
  - coveralls